# Cloudflare Pages 配置文件 - 存档点恢复版本
name = "kemono-shares-api"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

# 构建配置
[build]
command = "npm run build:pages:static"
output_directory = "out"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "10"

# 安全头配置
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# 重定向配置 - 匹配存档点设置
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# 环境变量将在 Cloudflare Pages 控制台中设置
# 这里只保留基本配置 