# Cloudflare Pages 专用配置文件
# 这个文件专门用于 Cloudflare Pages 部署

name = "kemono-shares-api"
compatibility_date = "2024-07-01"

# Pages 构建配置
pages_build_output_dir = ".next"

[build]
command = "npm run build"

# 环境变量
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_APP_URL = "https://2kawaii.com"

# KV 命名空间
[[kv_namespaces]]
binding = "SHARE_DATA_KV"
id = "77b81f5b787b449e931fa6a51263b38c"
preview_id = "2d7d8b533f3049b89d808fbb569bb09c" 