# Cloudflare Pages 配置文件
name = "kemono-shares-api"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

# Pages配置 - 使用 .vercel/output for next-on-pages
pages_build_output_dir = ".vercel/output"

# KV 命名空间配置
[[kv_namespaces]]
binding = "SHARE_DATA_KV"
id = "77b81f5b787b449e931fa6a51263b38c"
preview_id = "2d7d8b533f3049b89d808fbb569bb09c"

# 全局环境变量
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_APP_URL = "https://2kawaii.com"
KIE_AI_API_KEY = "2800cbec975bf014d815f4e5353c826a"
KIE_AI_API_KEY_2 = "6a77fe3ca6856170f6618d4f249cfc6a"
KIE_AI_API_KEY_3 = "db092e9551f4631136cab1b141fdfd21"
KIE_AI_API_KEY_4 = "3f06398cf9d8dc02a243f2dd5f2f9489"
KIE_AI_API_KEY_5 = "c982688b5c6938943dd721ed1d576edb"
KIE_AI_4O_BASE_URL = "https://api.kie.ai"
KIE_AI_USER_ID = "j2983236233@gmail.com"
KIE_AI_EDGE_BASE = "https://api.kie.ai/api/v1"
IMGBB_API_KEY = "f62c400dfa7cffdbe66ebcdbf6f2d783"
CLOUDFLARE_R2_ACCOUNT_ID = "9a5ff316a26b8abb696af519e515d2de"
CLOUDFLARE_R2_ACCESS_KEY_ID = "8072494c2581823ba4eefd7da9e910ca"
CLOUDFLARE_R2_SECRET_ACCESS_KEY = "ee959470338a6f01c1f25fcf877e17fd3dfcca623ae6b94f6bfc8a3425b06b59"
CLOUDFLARE_R2_BUCKET_NAME = "kemono-uploadimage"
CLOUDFLARE_R2_PUBLIC_URL = "https://pub-9ea5461e9e8b418caecb7e5b7748bdea.r2.dev"
CLOUDFLARE_R2_AFTERIMAGE_BUCKET_NAME = "kemono-afterimage"
CLOUDFLARE_R2_AFTERIMAGE_PUBLIC_URL = "https://pub-d00e7b41917848d1a8403c984cb62880.r2.dev"
CLOUDFLARE_API_TOKEN = "HJ5ugyPnYiDdOjK_OjsFoZI8KgVytyIjN4GWNpZ9"
CLOUDFLARE_ACCOUNT_ID = "9a5ff316a26b8abb696af519e515d2de"
CF_PAGES = "true"
CF_PAGES_URL = "https://2kawaii.com"

# 生产环境变量
[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_APP_URL = "https://2kawaii.com"
KIE_AI_API_KEY = "2800cbec975bf014d815f4e5353c826a"
KIE_AI_API_KEY_2 = "6a77fe3ca6856170f6618d4f249cfc6a"
KIE_AI_API_KEY_3 = "db092e9551f4631136cab1b141fdfd21"
KIE_AI_API_KEY_4 = "3f06398cf9d8dc02a243f2dd5f2f9489"
KIE_AI_API_KEY_5 = "c982688b5c6938943dd721ed1d576edb"
KIE_AI_4O_BASE_URL = "https://api.kie.ai"
KIE_AI_USER_ID = "j2983236233@gmail.com"
KIE_AI_EDGE_BASE = "https://api.kie.ai/api/v1"
IMGBB_API_KEY = "f62c400dfa7cffdbe66ebcdbf6f2d783"
CLOUDFLARE_R2_ACCOUNT_ID = "9a5ff316a26b8abb696af519e515d2de"
CLOUDFLARE_R2_ACCESS_KEY_ID = "8072494c2581823ba4eefd7da9e910ca"
CLOUDFLARE_R2_SECRET_ACCESS_KEY = "ee959470338a6f01c1f25fcf877e17fd3dfcca623ae6b94f6bfc8a3425b06b59"
CLOUDFLARE_R2_BUCKET_NAME = "kemono-uploadimage"
CLOUDFLARE_R2_PUBLIC_URL = "https://pub-9ea5461e9e8b418caecb7e5b7748bdea.r2.dev"
CLOUDFLARE_R2_AFTERIMAGE_BUCKET_NAME = "kemono-afterimage"
CLOUDFLARE_R2_AFTERIMAGE_PUBLIC_URL = "https://pub-d00e7b41917848d1a8403c984cb62880.r2.dev"
CLOUDFLARE_API_TOKEN = "HJ5ugyPnYiDdOjK_OjsFoZI8KgVytyIjN4GWNpZ9"
CLOUDFLARE_ACCOUNT_ID = "9a5ff316a26b8abb696af519e515d2de"
CF_PAGES = "true"
CF_PAGES_URL = "https://2kawaii.com"

# 预览环境变量
[env.preview.vars]
NODE_ENV = "development"
NEXT_PUBLIC_APP_URL = "https://kemono-shares-api-dev.y2983236233.workers.dev" 